### ISSUE TITLE
Zapis danych

### ISSUE THREAD

**Issue by JKGplay** [JKGplay/rypygy#1]
Dodać funkcję zapisu danych po zamknięciu aplikacji za pomocą SharedPreferences.
[Link do dokumentacji.](https://developer.android.com/training/data-storage/shared-preferences#java)
Zrobić osobne klucze dla:
- nazwy postaci
- hp
- money
- level
- xp

**Comment by skytokox** [comment]
Albion Online to sandbox MMORPG, w którym to Ty piszesz własną historię, zamiast podążać wytyczoną ścieżką. Odkrywaj ogromny otwarty świat. Wszystko, co robisz, wpływa na zależną od gracza ekonomię Albionu. Każdy element ekwipunku jest tworzony przez graczy z surowców, które sami zbierają. Twój ekwipunek decyduje o tym, kim jesteś. Zamiana z rycerza na maga jest tak prosta, jak zmiana zbroi i broni. Możesz też połączyć elementy obu klas.  Ruszaj w głąb lochów, gdzie znajdziesz zarówno bogactwo jak i zagrożenia. Zrelaksuj się na własnej wyspie, na której możesz postawić dom, sadzić rośliny i hodować zwierzęta. Chwyć za wędkę i ruszaj w kierunku jezior, rzek i oceanów Albionu.  Dołącz do gildii, graj z innymi! Bierz udział w ogromnych bitwach PVP i zagarnij dla siebie kawałek świata! To jest Albion Online.
